"""empty message

Revision ID: d081486c8b37
Revises: cec84ddaaafc
Create Date: 2024-06-01 18:31:54.892851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd081486c8b37'
down_revision = 'cec84ddaaafc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
